default/urls.py
from django.conf.urls import patterns, include, url
import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'default.views.home', name='home'),
    # url(r'^default/', include('default.foo.urls')),
    url(r'^$', views.index),
    url(r'^edit/$', views.edit),
    url(r'^make/(?P<id>\d+)/$', views.make),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^.*/$', views.error),
)

default/models.py
from django.db import models
from django.forms import ModelForm

from django.db.models.signals import post_save as save
from django.db.models.signals import post_delete as delete


class Personal(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    dob = models.DateField()
    bio = models.TextField()
    phone = models.CharField(max_length=12)
    email = models.EmailField()

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)


class PersonalForm(ModelForm):
    class Meta:
        model = Personal
        fields = ['email', 'phone', 'bio', 'dob', 'last_name', 'first_name']


class Requests(models.Model):
    request = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now=True)


class Operations(models.Model):
    sender = models.CharField(max_length=100)
    action = models.CharField(max_length=20)
    time = models.DateTimeField(auto_now=True)


def save_listener(sender, **kwargs):
    name = sender=sender.__name__
    if name is not 'Operations':
        query = Operations(sender=name, action='save')
        query.save()


def delete_listener(sender, **kwargs):
    name = sender=sender.__name__
    if name is not 'Operations':
        query = Operations(sender=name, action='delete')
        query.save()

save.connect(save_listener)
delete.connect(delete_listener)

default/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, Http404, HttpResponse
from models import Personal, PersonalForm


def index(request):
    return render_to_response('index.html', {'data': Personal.objects.get(id=1), },
                                context_instance=RequestContext(request))


def edit(request):
    data = Personal.objects.get(id=1)
    if request.method == 'POST':
        form = PersonalForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = PersonalForm(instance=data)

    return render_to_response('edit.html', {'form': form, })


def make(request, id):
    try:
        data = Personal.objects.get(id=id)
    except:
        raise Http404()

    return render_to_response('make.html', {'id':id})

def error(request):
    return HttpResponse('Invalid Request - %s' % request.path)

default/templates/edit.html
{% extends 'layout.html' %}
{% block content %}

<form action='' method='POST'>
<table>
    {{ form.as_table }}
    <td colspan='2'><input type="submit" value="Submit"></td>
</table>
</form>

{% endblock %}

default/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<p style='font-weight:bold;'>{{ data }}</p>
<ul>
    <li>
        Date of birth: {{ data.dob }}
    </li>
    <li>
        Email: {{ data.email }}
    </li>
    <li>
        Phone: {{ data.phone }}
    </li>
    <li>
        Bio: {{ data.bio }}
    </li>
</ul>
<a href='/edit/'>Edit this info</a>
{% endblock %}

default/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Django Playground</title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
        <script src='http://code.jquery.com/jquery-1.9.1.min.js'></script>
        <script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
        <script>
            $(function() {
                $("#id_dob").datepicker({
                        changeMonth: true,
                        changeYear: true,
                        dateFormat: 'dd/mm/yy'
                    });
                });
        </script>
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

default/templates/make.html
{% extends 'layout.html' %}
{% load makelink %}
{% block content %}
{% makeLink id %}
{% endblock %}